# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1

# --- Builder stage ---
# Use official Bun image for building
FROM oven/bun:latest AS builder

WORKDIR /app
# Copy everything
COPY . .

# Install dependencies and build production bundle
RUN bun install
RUN bun run build:prod

# --- Runtime stage ---
FROM node:lts-alpine AS runtime
WORKDIR /app

# Copy built distribution
COPY --from=builder /app/dist ./dist

# Expose default port if needed (MCP over stdio does not need channel)
# Default command to run the MCP server
CMD ["node", "dist/index.js"]
